### ISSUE TITLE
Peer does not always write final piece

### ISSUE THREAD

**Issue by emallson** [vcrawford/NetworkingProject#2]
```
[~/Code/NetworkingProject]$ grep "has downloaded" *.log
log_peer_1002.log:[2017-04-04 16:12:29,822] [INFO] [p.networking PeerProcess.java:524] Peer 1002 has downloaded the complete file.
log_peer_1003.log:[2017-04-04 16:12:31,608] [INFO] [p.networking PeerProcess.java:524] Peer 1003 has downloaded the complete file.
log_peer_1004.log:[2017-04-04 16:12:36,924] [INFO] [p.networking PeerProcess.java:524] Peer 1004 has downloaded the complete file.
log_peer_1005.log:[2017-04-04 16:12:36,673] [INFO] [p.networking PeerProcess.java:524] Peer 1005 has downloaded the complete file.
log_peer_1006.log:[2017-04-04 16:12:40,233] [INFO] [p.networking PeerProcess.java:524] Peer 1006 has downloaded the complete file.
```

and yet
```
[~/Code/NetworkingProject]$ md5sum peer_*/*.dat
377e53fb78c47fa58dc2f637afe1000c  peer_1001/TheFile.dat
377e53fb78c47fa58dc2f637afe1000c  peer_1002/TheFile.dat
377e53fb78c47fa58dc2f637afe1000c  peer_1003/TheFile.dat
377e53fb78c47fa58dc2f637afe1000c  peer_1004/TheFile.dat
e8cdde4ee55af87f18b9381c18f70953  peer_1005/TheFile.dat
377e53fb78c47fa58dc2f637afe1000c  peer_1006/TheFile.dat
```

Unsure why this is happening. By the timestamps, we can see that peer 1005 was actually *not* the last one to download the complete file, and yet somewhere along the line it appears to have failed to write a piece. Further still, no error is reported.

**Comment by emallson** [comment]
I added a log message for when a piece is successfully written, and every time that one file is missing a piece, the log still has 306 successful messages.

**Comment by 9autilus** [comment]
Issue is still present. Despite peer printing "Peer 100x has downloaded the complete file." the `verify_completion.py` utility prints out only 99.x% completion. I don't doubt the utility because it prints 100% completion when I disable sending 'have' messages (just one sender, hence less complications).
